api_v2/urls.py
from django.urls import include, path
from rest_framework import routers
from api_v2 import views
from api_v2.views import LogoutView, PubViewSet, PubListView, PubDetailView
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()
router.register(r'publications', views.PubViewSet)

app_name = 'api_v2'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('like/<int:pk>', PubViewSet.as_view({'get': 'like_it'}), name='like_it'),
    path('logout/', LogoutView.as_view(), name='api_token_delete'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('publications.urls')),
    path('api/v2/', include('api_v2.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path
from .views import IndexView, PublicationCreateView, PublicationView, like_publication

app_name = 'publications'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('publications/create', PublicationCreateView.as_view(), name='create'),
    path('publications/<int:publication_pk>', PublicationView.as_view(), name='detail'),
    path('like/<int:pk>', like_publication, name='like_publication')
]

publications/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Publication(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=False, blank=False, related_name='publications')
    image = models.ImageField(blank=False, upload_to='images', verbose_name='Публикация')
    description = models.TextField(max_length=2000, blank=False, verbose_name='Описание')
    likes_counter = models.IntegerField(null=True, blank=False, default=0, verbose_name='Число лайков')
    comments_counter = models.IntegerField(null=True, blank=False, default=0, verbose_name='Число комментариев')
    likes = models.ManyToManyField(get_user_model(), related_name='posts')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

publications/forms.py
from django import forms
from publications.models import Publication


class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ['image', 'description']
        labels = {'image': 'Image', 'description': 'Description'}


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False)

publications/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import View, TemplateView, FormView, ListView, DetailView, CreateView, DeleteView
from django.contrib.auth import get_user_model
from publications.models import Publication
from publications.forms import PublicationForm


def like_publication(request, pk):
    publication = get_object_or_404(Publication, id=request.POST.get('publication_id'))
    if request.user in publication.likes.all():
        publication.likes.remove(request.user)
        publication.likes_counter = publication.likes.count()
    else:
        publication.likes.add(request.user)
        publication.likes_counter = publication.likes.count()
    publication.save()
    return HttpResponseRedirect(reverse('publications:detail', args=[str(pk)]))


class IndexView(ListView):
    context_object_name = 'publications'
    model = Publication
    template_name = 'publication/publication_list.html'


class PublicationCreateView(CreateView):
    model = Publication
    form_class = PublicationForm
    template_name = 'publication/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['user'] = self.request.user
        return context

    def form_valid(self, form):
        user = get_object_or_404(get_user_model(), pk=self.request.user.pk)
        publication = form.save(commit=False)
        publication.user = user
        print(publication)
        publication.save()
        return redirect('publications:index')
                        # publication_pk=publication.pk)


class PublicationView(DetailView):
    template_name = 'publication/publication.html'
    model = Publication
    pk_url_kwarg = 'publication_pk'

publications/templates/publication/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Add new publication{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
    <h1>Create publication</h1>
    <form action="{% url "publications:create" %}{% if next_path %}?next={{ next_path }}{% endif %}"
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button class="btn btn-success">Sign Up</button>
    </form>
    {% else %}
        <h1>Please login firsts</h1>
    {% endif %}
{% endblock %}

publications/templates/publication/publication.html
{% extends 'base.html' %}

{% block title %}Publications{% endblock %}

{% block content %}
<h1> {{ publication.user }}'s publication </h1>
    <br>
    <div class="card" style="width: 40rem;">
      <img class="card-img-top" src="{{ publication.image.url }}" alt="Card image cap">
      <div class="card-body">
        <p class="card-title">
          {% if user.is_authenticated %}
          <form action="{% url 'publications:like_publication' publication.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" name="publication_id" value="{{ publication.id }}" class="btn btn-primary">

                {% if request.user in publication.likes.all %}
                    Unlike 
                {% else  %}
                    Like
                {% endif %} 
          {% endif %}
            </button>
          </form>
            &nbsp;
            <b> | &nbsp; {{ publication.likes.all.count }} people liked this &nbsp; | &nbsp;
                {{ publication.comments_counter }} сomments </b></p>
        <p class="card-text">{{ publication }}</p>
        <a href="{% url 'publications:index' %}" class="btn btn-primary">Back to the list</a>
      </div>
    </div>
    <br>
{% endblock %}

publications/templates/publication/publication_list.html
{% extends 'base.html' %}

{% block title %}Publications{% endblock %}

{% block content %}
<style>
  .truncate {
    /*background: #f4eddf; !* Цвет фона *!*/
    padding: 10px;
    /* Поля вокруг текста */
    white-space: nowrap;
    /* Текст не переносится */
    overflow: hidden;
    /* Обрезаем всё за пределами блока */
    text-overflow: ellipsis;
    /* Добавляем многоточие */
  }
</style>

<h1>Publications list</h1>
<br>
{% for publication in publications %}
<div class="card" style="width: 40rem;">
  <img class="card-img-top" src="{{ publication.image.url }}" alt="Card image cap">
  <div class="card-body">
    <p class="card-text; truncate">{{ publication }}</p>
    <b id="b{{publication.id}}"> | &nbsp; {{ publication.likes.all.count }} people liked this &nbsp; | &nbsp;
      {{ publication.comments_counter }} сomments </b>
      
      <input type="hidden" value="{{request.user.id}}" id="request.user.id">
      {% if user.is_authenticated %}
      <a href="" name="like-btn" id="{{publication.id}}" class="btn btn-primary like-btn">
      {% if request.user in publication.likes.all %}
      Unlike
      {% else %}
      Like
      {% endif %}
      {% endif %}
    </a>
    <a href="{% url 'publications:detail' publication.pk %}" class="btn btn-primary">More</a>
  </div>
</div>
<br>
{% endfor %}
{% endblock %}