accounts/urls.py
from django.urls import path
from accounts import views as accounts_views

app_name = 'accounts'

urlpatterns = [
    path('login/', accounts_views.LoginView.as_view(), name='login'),
    path('logout/', accounts_views.LogoutView.as_view(), name='logout'),
    path('register/', accounts_views.RegisterView.as_view(), name='register'),
    path('<int:user_pk>/', accounts_views.ProfileView.as_view(), name='profile'),
    path('', accounts_views.UserListView.as_view(), name='user_list'),
    # path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    # path('change_password/', ChangePasswordView.as_view(), name='change_password')

]

api_v2/urls.py
from django.urls import include, path
from rest_framework import routers
from api_v2 import views
from api_v2.views import LogoutView, PubViewSet, PubListView, PubDetailView
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()
router.register(r'publications', views.PubViewSet)

app_name = 'api_v2'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('like/<int:pk>', PubViewSet.as_view({'get': 'like_it'}), name='like_it'),
    path('logout/', LogoutView.as_view(), name='api_token_delete'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('publications.urls')),
    path('api/v2/', include('api_v2.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path
from .views import IndexView, PublicationCreateView, PublicationView, like_publication

app_name = 'publications'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('publications/create', PublicationCreateView.as_view(), name='create'),
    path('publications/<int:publication_pk>', PublicationView.as_view(), name='detail'),
    path('like/<int:pk>', like_publication, name='like_publication')
]

publications/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Publication(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=False, blank=False, related_name='publications')
    image = models.ImageField(blank=False, upload_to='images', verbose_name='Публикация')
    description = models.TextField(max_length=2000, blank=False, verbose_name='Описание')
    likes_counter = models.IntegerField(null=True, blank=False, default=0, verbose_name='Число лайков')
    comments_counter = models.IntegerField(null=True, blank=False, default=0, verbose_name='Число комментариев')
    likes = models.ManyToManyField(get_user_model(), related_name='posts')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

publications/forms.py
from django import forms
from publications.models import Publication


class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ['image', 'description']
        labels = {'image': 'Image', 'description': 'Description'}


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False)

publications/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import View, TemplateView, FormView, ListView, DetailView, CreateView, DeleteView
from django.contrib.auth import get_user_model
from publications.models import Publication
from publications.forms import PublicationForm


def like_publication(request, pk):
    publication = get_object_or_404(Publication, id=request.POST.get('publication_id'))
    if request.user in publication.likes.all():
        publication.likes.remove(request.user)
        publication.likes_counter = publication.likes.count()
    else:
        publication.likes.add(request.user)
        publication.likes_counter = publication.likes.count()
    publication.save()
    return HttpResponseRedirect(reverse('publications:detail', args=[str(pk)]))


class IndexView(ListView):
    context_object_name = 'publications'
    model = Publication
    template_name = 'publication/publication_list.html'


class PublicationCreateView(CreateView):
    model = Publication
    form_class = PublicationForm
    template_name = 'publication/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['user'] = self.request.user
        return context

    def form_valid(self, form):
        user = get_object_or_404(get_user_model(), pk=self.request.user.pk)
        publication = form.save(commit=False)
        publication.user = user
        print(publication)
        publication.save()
        return redirect('publications:index')
                        # publication_pk=publication.pk)


class PublicationView(DetailView):
    template_name = 'publication/publication.html'
    model = Publication
    pk_url_kwarg = 'publication_pk'

publications/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light d-flex align-items-center" style="z-index: 1">
        <div class=" d-flex align-items-baseline">
        {% if request.user.is_authenticated %}
            <a class="ms-5 row d-flex  pt-3" href="{% url 'publications:index' %}"><img style="width:110px"  src="{% static 'img/icon/insta-logo.png' %}" alt="insta"></a>
        {% endif %}
            <ul class="menu col-md-10 d-flex justify-content-center" style="font-size: 25px;">
                {% if user.is_authenticated %}
                    <li>
                    <form class="ms-5  ps-5 menu d-flex justify-content-center" method="get">
                        <input class="form-control me-2" name="search" type="search" placeholder="Search" value="{{ form.search.value|default:'' }}" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">Search</button>
                    </form>
                </li>
                <li><a href="{% url 'accounts:profile' user.pk %}"><img style="width:25px" src="{% static 'img/icon/icon-house.png' %}" alt="house"></a></li>|
                <li><a href="{% url 'accounts:user_list' %}"><img style="width:25px" src="{% static 'img/icon/icon-messenger.png' %}" alt="messenger"></a></li>|
                <li><a href="{% url 'publications:create' %}?next={{ request.path }}"><img style="width:25px" src="{% static 'img/icon/icon-instagram-post.png' %}" alt="new publication"></a></li>|
                <li class="menu-right">
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-light" id="logout" style="margin-left: 15px">Logout</button>
                    </form>
                    <script>
                        const getlogout = function () {
                            let logout = document.getElementById('logout')
                            console.log('Weee');
                            $.ajax({
                                url: 'http://localhost:8000/api/v2/logout/',
                                method: 'post',
                                headers: { 'Authorization': 'Token ' + localStorage.getItem('apiToken') },
                                dataType: 'json',
                                contentType: 'application/json',
                                success: function (response, status) { localStorage.removeItem('apiToken', response.token); },
                                error: function (response, status) { console.log(response); }
                            });
                        }
                        let exit = logout.addEventListener('click', getlogout)
                    </script>
                </li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}?next={{ request.path }}" style="color: #ffc122">Login</a></li>|
                    <li><a href="{% url 'accounts:register' %}?next={{ request.path }}" style="color: #ffc122">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block menu_links %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
  <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
  <script src="{% static 'js/script.js'%}"></script>
</body>
</html>